'use strict';

const { HUMAN_PLAY_CATALOG } = require('./humanPlayCatalog');

/**
 * Taxonomy of “normal player” capabilities for Jarvys.
 *
 * - **core** — Already registered in `bot.js` (main roadmap).
 * - **live-addon** — Implemented and merged via `extraPlayerSkills.js`.
 * - **extended** — Handled by `skills/extendedPlayerDispatch.js` (best-effort automation; some tasks return guidance only).
 *
 * The canonical core set is the `skills` map in `bot.js`; entries here document intent.
 */

const SKILL_CATALOG = [
  /* ——— Core roadmap (implemented in bot.js) ——— */
  { id: 'init_structure', category: 'bootstrap', title: 'State bootstrap', description: 'Internal progress init.', status: 'core' },
  { id: 'connect', category: 'bootstrap', title: 'Join server', description: 'Spawn and session.', status: 'core' },
  { id: 'goto_test', category: 'movement', title: 'First anchor', description: 'Pathfind away from spawn / to waypoint.', status: 'core' },
  { id: 'explore_nearby', category: 'movement', title: 'Explore chunks', description: 'Break stuck gathers; load terrain.', status: 'core' },
  { id: 'retreat', category: 'survival', title: 'Flee danger', description: 'Low HP + mobs; back off.', status: 'core' },
  { id: 'eat_if_needed', category: 'survival', title: 'Eat food', description: 'Consume inventory food when hungry.', status: 'core' },
  { id: 'sleep_in_bed', category: 'survival', title: 'Sleep', description: 'Skip night / phantoms.', status: 'core' },
  { id: 'lighten_inventory', category: 'inventory', title: 'Drop junk', description: 'Free slots; drop excess stone/dirt.', status: 'core' },
  { id: 'collect_wood', category: 'gathering', title: 'Mine logs', description: 'Starter and bulk wood.', status: 'core' },
  { id: 'collect_more_wood', category: 'gathering', title: 'More logs', description: 'Mid-game wood.', status: 'core' },
  { id: 'collect_wood_for_house', category: 'gathering', title: 'House timber', description: 'Target log count for shelter.', status: 'core' },
  { id: 'collect_cobblestone', category: 'gathering', title: 'Stone → cobble', description: 'Mine stone for cobble.', status: 'core' },
  { id: 'collect_coal', category: 'gathering', title: 'Coal ore', description: 'Fuel and torches.', status: 'core' },
  { id: 'collect_iron_ore', category: 'gathering', title: 'Iron ore', description: 'Overworld / deepslate iron.', status: 'core' },
  { id: 'collect_gravel_for_flint', category: 'gathering', title: 'Gravel / flint', description: 'Flint for flint & steel.', status: 'core' },
  { id: 'collect_diamond_ore', category: 'gathering', title: 'Diamonds', description: 'Cave / deepslate diamonds.', status: 'core' },
  { id: 'collect_obsidian', category: 'gathering', title: 'Obsidian', description: 'Portal frame blocks.', status: 'core' },
  { id: 'collect_blaze_rods', category: 'nether', title: 'Blaze rods', description: 'Nether fortress.', status: 'core' },
  { id: 'collect_ender_pearls', category: 'combat', title: 'Ender pearls', description: 'Endermen farm/hunt.', status: 'core' },
  { id: 'hunt_food', category: 'gathering', title: 'Hunt animals', description: 'Passive mobs for meat.', status: 'core' },
  { id: 'kill_enemy', category: 'combat', title: 'Fight hostile', description: 'Clear nearby threat.', status: 'core' },
  { id: 'craft_planks', category: 'crafting', title: 'Planks', description: 'Logs → planks.', status: 'core' },
  { id: 'craft_sticks', category: 'crafting', title: 'Sticks', description: 'Planks → sticks.', status: 'core' },
  { id: 'craft_crafting_table', category: 'crafting', title: 'Crafting table', description: '2×2 → table item.', status: 'core' },
  { id: 'craft_wood_pick', category: 'crafting', title: 'Wooden pick', description: 'First pickaxe.', status: 'core' },
  { id: 'craft_stone_pick', category: 'crafting', title: 'Stone pick', description: 'Stone-tier mining.', status: 'core' },
  { id: 'craft_stone_sword', category: 'crafting', title: 'Stone sword', description: 'Early melee.', status: 'core' },
  { id: 'craft_stone_axe', category: 'crafting', title: 'Stone axe', description: 'Chop + combat.', status: 'core' },
  { id: 'craft_wood_axe', category: 'crafting', title: 'Wooden axe', description: 'Backup chopper.', status: 'core' },
  { id: 'craft_torch', category: 'crafting', title: 'Torches', description: 'Light sources.', status: 'core' },
  { id: 'craft_chest', category: 'crafting', title: 'Chest', description: 'Storage block.', status: 'core' },
  { id: 'craft_furnace', category: 'crafting', title: 'Furnace', description: 'Smelting block.', status: 'core' },
  { id: 'craft_bed', category: 'crafting', title: 'Bed', description: 'Spawn / sleep.', status: 'core' },
  { id: 'craft_iron_pickaxe', category: 'crafting', title: 'Iron pick', description: 'Diamond / obsidian prep.', status: 'core' },
  { id: 'craft_iron_sword', category: 'crafting', title: 'Iron sword', description: 'Stronger melee.', status: 'core' },
  { id: 'craft_shears', category: 'crafting', title: 'Shears', description: 'Wool / vines / honeycomb.', status: 'core' },
  { id: 'craft_iron_bucket', category: 'crafting', title: 'Bucket', description: 'Fluids and milk.', status: 'core' },
  { id: 'craft_iron_armor_set', category: 'crafting', title: 'Iron armor', description: 'Full iron set over time.', status: 'core' },
  { id: 'craft_stone_shovel', category: 'crafting', title: 'Stone shovel', description: 'Gravel / dirt fast.', status: 'core' },
  { id: 'craft_flint_and_steel', category: 'crafting', title: 'Flint & steel', description: 'Ignite portal.', status: 'core' },
  { id: 'craft_diamond_pickaxe', category: 'crafting', title: 'Diamond pick', description: 'Obsidian mining.', status: 'core' },
  { id: 'craft_blaze_powder', category: 'crafting', title: 'Blaze powder', description: 'From blaze rods.', status: 'core' },
  { id: 'craft_eyes_of_ender', category: 'crafting', title: 'Eyes of ender', description: 'Stronghold triangulation.', status: 'core' },
  { id: 'craft_house_planks', category: 'crafting', title: 'Bulk planks', description: 'House shell material.', status: 'core' },
  { id: 'place_crafting_table', category: 'building', title: 'Place table', description: '3×3 crafting access.', status: 'core' },
  { id: 'place_bed', category: 'building', title: 'Place bed', description: 'Spawn point.', status: 'core' },
  { id: 'place_chest', category: 'building', title: 'Place chest', description: 'Base storage.', status: 'core' },
  { id: 'place_furnace', category: 'building', title: 'Place furnace', description: 'Smelting station.', status: 'core' },
  { id: 'build_wooden_house', category: 'building', title: 'Wooden house', description: 'Floor/walls/roof shell.', status: 'core' },
  { id: 'build_nether_portal', category: 'nether', title: 'Nether portal', description: 'Frame + ignite.', status: 'core' },
  { id: 'fill_water_bucket', category: 'fluids', title: 'Fill bucket', description: 'Water source → water bucket.', status: 'core' },
  { id: 'place_water_source', category: 'fluids', title: 'Place water', description: 'Infinite water pit.', status: 'core' },
  { id: 'shear_sheep', category: 'gathering', title: 'Shear sheep', description: 'Wool without killing.', status: 'core' },
  { id: 'smelt_iron_ingots', category: 'processing', title: 'Smelt iron', description: 'Furnace → iron ingots.', status: 'core' },
  { id: 'equip_armor', category: 'gear', title: 'Equip armor', description: 'Best armor from inventory.', status: 'core' },
  { id: 'equip_weapon', category: 'gear', title: 'Equip weapon', description: 'Best melee from inventory.', status: 'core' },
  { id: 'equip_iron_kit', category: 'gear', title: 'Equip iron kit', description: 'Iron armor + weapon swap.', status: 'core' },
  { id: 'enter_nether', category: 'nether', title: 'Enter Nether', description: 'Dimension travel.', status: 'core' },
  { id: 'find_stronghold', category: 'endgame', title: 'Find stronghold', description: 'Eye throwing / travel.', status: 'core' },
  { id: 'fill_end_portal', category: 'endgame', title: 'Fill End portal', description: 'Eyes in frame.', status: 'core' },
  { id: 'enter_end', category: 'endgame', title: 'Enter End', description: 'Jump into portal.', status: 'core' },
  { id: 'destroy_end_crystals', category: 'endgame', title: 'Break crystals', description: 'Pillar crystals.', status: 'core' },
  { id: 'kill_ender_dragon', category: 'endgame', title: 'Kill dragon', description: 'Boss fight.', status: 'core' },
  { id: 'prep_end_combat', category: 'endgame', title: 'End prep', description: 'Bow / arrows / food.', status: 'core' },
  { id: 'shortcut_villager', category: 'social', title: 'Villager shortcut', description: 'Optional trades.', status: 'core' },
  { id: 'shortcut_enchant', category: 'gear', title: 'Enchant shortcut', description: 'Table if nearby.', status: 'core' },
  { id: 'shortcut_brew', category: 'alchemy', title: 'Brew shortcut', description: 'Stand if nearby.', status: 'core' },
  { id: 'build_potato_farm', category: 'farming', title: 'Potato farm', description: 'Optional food plot.', status: 'core' },
  { id: 'collect_potatoes', category: 'farming', title: 'Harvest potatoes', description: 'Farm output.', status: 'core' },
  { id: 'smelt_baked_potatoes', category: 'processing', title: 'Baked potatoes', description: 'Smelt potatoes.', status: 'core' },
  { id: 'postgame_end_city', category: 'postgame', title: 'End cities', description: 'Optional elytra path.', status: 'core' },
  { id: 'postgame_wither_prep', category: 'postgame', title: 'Wither prep', description: 'Optional boss mats.', status: 'core' },

  /* ——— Live add-ons (implemented, merged in bot.js) ——— */
  { id: 'collect_grass_seeds', category: 'farming', title: 'Grass seeds', description: 'Break grass for wheat seeds.', status: 'live-addon' },
  { id: 'craft_stone_hoe', category: 'crafting', title: 'Stone hoe', description: 'Till farmland.', status: 'live-addon' },
  { id: 'till_plant_wheat', category: 'farming', title: 'Plant wheat', description: 'Hoe + seeds near water.', status: 'live-addon' },
  { id: 'harvest_mature_wheat', category: 'farming', title: 'Harvest wheat', description: 'Break mature crops.', status: 'live-addon' },
  { id: 'craft_bread', category: 'crafting', title: 'Bread', description: '3 wheat → food.', status: 'live-addon' },
  { id: 'milk_cow', category: 'gathering', title: 'Milk cow', description: 'Bucket → milk (buff clear / cake prep).', status: 'live-addon' },
  { id: 'collect_sand', category: 'gathering', title: 'Mine sand', description: 'Beaches / deserts for glass.', status: 'live-addon' },
  { id: 'smelt_glass', category: 'processing', title: 'Smelt glass', description: 'Sand → glass blocks.', status: 'live-addon' },
  { id: 'collect_sugar_cane', category: 'gathering', title: 'Sugar cane', description: 'Paper / sugar / books path.', status: 'live-addon' },
  { id: 'craft_paper', category: 'crafting', title: 'Paper', description: 'Sugar cane → paper.', status: 'live-addon' },
  { id: 'craft_fishing_rod', category: 'crafting', title: 'Fishing rod', description: 'Sticks + string.', status: 'live-addon' },

  /* ——— Extended player skills (implemented via extendedPlayerDispatch.js; some best-effort / partial) ——— */
  { id: 'fish_for_food', category: 'gathering', title: 'Fish', description: 'AFK fish for fish / loot.', status: 'extended' },
  { id: 'breed_animals', category: 'farming', title: 'Breed livestock', description: 'Wheat/carrots → baby animals.', status: 'extended' },
  { id: 'collect_eggs', category: 'gathering', title: 'Collect eggs', description: 'Pickup chicken eggs.', status: 'extended' },
  { id: 'strip_logs', category: 'building', title: 'Strip logs', description: 'Axe → stripped log aesthetic.', status: 'extended' },
  { id: 'use_campfire_cook', category: 'processing', title: 'Campfire cooking', description: 'Cook on campfire without furnace UI.', status: 'extended' },
  { id: 'use_smoker', category: 'processing', title: 'Smoker', description: 'Fast food smelting.', status: 'extended' },
  { id: 'use_blast_furnace', category: 'processing', title: 'Blast furnace', description: 'Fast ore smelting.', status: 'extended' },
  { id: 'use_stonecutter', category: 'building', title: 'Stonecutter', description: 'Stone variants.', status: 'extended' },
  { id: 'use_loom', category: 'building', title: 'Loom', description: 'Banner patterns.', status: 'extended' },
  { id: 'use_cartography', category: 'utility', title: 'Cartography', description: 'Maps / locked maps.', status: 'extended' },
  { id: 'use_grindstone', category: 'gear', title: 'Grindstone', description: 'Disenchant / repair merge.', status: 'extended' },
  { id: 'use_smithing_table', category: 'gear', title: 'Smithing', description: 'Netherite upgrade / trims.', status: 'extended' },
  { id: 'use_anvil_repair', category: 'gear', title: 'Anvil repair', description: 'Combine / rename / repair.', status: 'extended' },
  { id: 'enchant_at_table', category: 'gear', title: 'Enchanting table', description: 'Spend levels + lapis.', status: 'extended' },
  { id: 'brew_potion', category: 'alchemy', title: 'Brewing stand', description: 'Potions from bases + reagents.', status: 'extended' },
  { id: 'fill_glass_bottles_water', category: 'fluids', title: 'Water bottles', description: 'Glass bottles on water.', status: 'extended' },
  { id: 'collect_honey', category: 'gathering', title: 'Bottle honey', description: 'Campfire + bottle on hive.', status: 'extended' },
  { id: 'shear_hive', category: 'gathering', title: 'Shear beehive', description: 'Honeycomb safely.', status: 'extended' },
  { id: 'collect_clay', category: 'gathering', title: 'Clay / terracotta', description: 'River clay balls.', status: 'extended' },
  { id: 'craft_bricks', category: 'crafting', title: 'Bricks', description: 'Clay balls → bricks.', status: 'extended' },
  { id: 'collect_kelp', category: 'gathering', title: 'Kelp', description: 'Underwater kelp for fuel.', status: 'extended' },
  { id: 'smelt_dried_kelp', category: 'processing', title: 'Dried kelp', description: 'Kelp block food / fuel.', status: 'extended' },
  { id: 'place_ladders_scaffold', category: 'building', title: 'Vertical build', description: 'Ladders / scaffolding up.', status: 'extended' },
  { id: 'ride_boat', category: 'movement', title: 'Boat travel', description: 'Cross water quickly.', status: 'extended' },
  { id: 'ride_minecart', category: 'movement', title: 'Minecart', description: 'Rails / powered rails.', status: 'extended' },
  { id: 'use_elytra', category: 'movement', title: 'Elytra flight', description: 'Firework boosting.', status: 'extended' },
  { id: 'throw_pearl_escape', category: 'movement', title: 'Pearl movement', description: 'Ender pearl clutch.', status: 'extended' },
  { id: 'place_blocks_fill', category: 'building', title: 'Bulk fill', description: 'Bridge / wall / floor assist.', status: 'extended' },
  { id: 'flatten_with_shovel', category: 'building', title: 'Terraform', description: 'Shovel paths / flatten.', status: 'extended' },
  { id: 'ignite_tnt', category: 'utility', title: 'TNT', description: 'Mining / traps.', status: 'extended' },
  { id: 'use_shield_block', category: 'combat', title: 'Shield timing', description: 'Block skeleton arrows.', status: 'extended' },
  { id: 'bow_snipe', category: 'combat', title: 'Bow kiting', description: 'Ranged safe DPS.', status: 'extended' },
  { id: 'splash_potion_combat', category: 'combat', title: 'Splash potions', description: 'Instant damage / healing.', status: 'extended' },
  { id: 'eat_golden_apple', category: 'survival', title: 'Golden apple', description: 'Absorption / regen clutch.', status: 'extended' },
  { id: 'use_totem', category: 'survival', title: 'Totem pop', description: 'Off-hand totem of undying.', status: 'extended' },
  { id: 'chorus_fruit_escape', category: 'survival', title: 'Chorus fruit', description: 'Random teleport escape.', status: 'extended' },
  { id: 'respawn_anchor_nether', category: 'nether', title: 'Respawn anchor', description: 'Nether respawn set.', status: 'extended' },
  { id: 'barter_piglin', category: 'nether', title: 'Piglin barter', description: 'Gold → loot.', status: 'extended' },
  { id: 'use_composter', category: 'farming', title: 'Composter', description: 'Bonemeal from crops.', status: 'extended' },
  { id: 'bone_meal_crops', category: 'farming', title: 'Bonemeal', description: 'Accelerate growth.', status: 'extended' },
  { id: 'carve_pumpkin', category: 'crafting', title: 'Carve pumpkin', description: 'Shears on pumpkin.', status: 'extended' },
  { id: 'dye_wool', category: 'crafting', title: 'Dye wool', description: 'Recolor blocks.', status: 'extended' },
  { id: 'rename_name_tag', category: 'social', title: 'Name tag', description: 'Anvil rename mobs.', status: 'extended' },
  { id: 'lead_mob', category: 'utility', title: 'Lead / leash', description: 'Move animals.', status: 'extended' },
  { id: 'trade_rotate_stock', category: 'social', title: 'Villager restock', description: 'Workstation + time cycle.', status: 'extended' },
  { id: 'cure_zombie_villager', category: 'social', title: 'Cure villager', description: 'Weakness + golden apple.', status: 'extended' },
  { id: 'raid_farm', category: 'combat', title: 'Raid farm', description: 'Bad omen → waves.', status: 'extended' },
  { id: 'iron_golem_guard', category: 'building', title: 'Iron golem', description: '4 iron + carved pumpkin.', status: 'extended' },
  { id: 'snow_golem_farm', category: 'farming', title: 'Snow golem', description: 'Snow farm.', status: 'extended' },
  { id: 'collect_bamboo', category: 'gathering', title: 'Bamboo', description: 'Jungle bamboo for sticks/scaffold.', status: 'extended' },
  { id: 'craft_scaffolding', category: 'crafting', title: 'Scaffolding', description: 'Bamboo climb stack.', status: 'extended' },
  { id: 'use_spyglass', category: 'utility', title: 'Spyglass', description: 'Scout terrain.', status: 'extended' },
  { id: 'brush_archaeology', category: 'gathering', title: 'Archaeology brush', description: 'Suspicious sand/gravel.', status: 'extended' },
  { id: 'trim_armor_smithing', category: 'gear', title: 'Armor trims', description: 'Smithing templates.', status: 'extended' },
  { id: 'wolf_armor_equip', category: 'gear', title: 'Wolf armor', description: 'Armored tamed wolf.', status: 'extended' },
  { id: 'place_light_level_safe', category: 'building', title: 'Mob-proof light', description: 'Light every spawnable tile.', status: 'extended' },
  { id: 'bucket_lava_safe', category: 'fluids', title: 'Lava bucket', description: 'Collect + place safely.', status: 'extended' },
  { id: 'create_netherite_gear', category: 'gear', title: 'Netherite upgrade', description: 'Template + ingot at smithing.', status: 'extended' },
  { id: 'firework_rocket_boost', category: 'utility', title: 'Firework boost', description: 'Elytra rockets.', status: 'extended' },
  { id: 'book_and_quill', category: 'utility', title: 'Writable book', description: 'Sign / notes.', status: 'extended' },
  { id: 'lectern_read', category: 'utility', title: 'Lectern', description: 'Read placed book.', status: 'extended' },
  { id: 'armor_stand_pose', category: 'building', title: 'Armor stand', description: 'Display gear.', status: 'extended' },
  { id: 'item_frame_map_wall', category: 'building', title: 'Map wall', description: 'Item frames + maps.', status: 'extended' },
  { id: 'redstone_door_trap', category: 'redstone', title: 'Simple redstone', description: 'Buttons / pressure / doors.', status: 'extended' },
  { id: 'hopper_sort', category: 'redstone', title: 'Hopper line', description: 'Item filtering / storage.', status: 'extended' },
  { id: 'auto_furnace_fuel_line', category: 'redstone', title: 'Auto-smelt', description: 'Fuel + ore hopper chain.', status: 'extended' },
  { id: 'xp_orb_collect_mend', category: 'gear', title: 'Mending repair', description: 'XP → durability.', status: 'extended' },
  { id: 'sneak_bridge_void', category: 'movement', title: 'Sneak bridging', description: 'Edge place blocks.', status: 'extended' },
  { id: 'pillar_up_jump', category: 'movement', title: 'Pillar up', description: 'Jump-place column.', status: 'extended' },
  { id: 'water_bucket_mlgb', category: 'fluids', title: 'Water MLG', description: 'Clutch fall with water.', status: 'extended' },
  { id: 'eat_dried_kelp_fast', category: 'survival', title: 'Kelp snacking', description: 'Low hunger saturation micro-food.', status: 'extended' },
  { id: 'organize_chest_tabs', category: 'inventory', title: 'Sort chests', description: 'Deposit by category.', status: 'extended' },
  { id: 'bundle_items', category: 'inventory', title: 'Bundles', description: 'Stack compress storage.', status: 'extended' },
  { id: 'shulker_box_kit', category: 'inventory', title: 'Shulker kits', description: 'Portable storage.', status: 'extended' },

  /* ——— Extra roadmap-style tasks ——— */
  { id: 'collect_netherrack', category: 'nether', title: 'Netherrack', description: 'Bulk netherrack for bridges.', status: 'extended' },
  { id: 'consume_cooked_meat', category: 'survival', title: 'Eat cooked food', description: 'Cooked meat or baked potato.', status: 'extended' },
  { id: 'craft_lantern', category: 'crafting', title: 'Lantern', description: 'Better light source.', status: 'extended' },
  { id: 'craft_iron_shovel', category: 'crafting', title: 'Iron shovel', description: 'Faster shoveling.', status: 'extended' },
  { id: 'craft_arrow_batch', category: 'crafting', title: 'Arrows', description: 'Ranged ammo batch.', status: 'extended' },
  { id: 'collect_flint_extra', category: 'gathering', title: 'More flint', description: 'Extra gravel mining.', status: 'extended' },
  { id: 'place_torch_hostile_cave', category: 'building', title: 'Cave torch', description: 'Light when dark / night.', status: 'extended' },
  { id: 'drink_milk_clear_effects', category: 'survival', title: 'Drink milk', description: 'Clear potion effects.', status: 'extended' },
  { id: 'sprint_jump_gap', category: 'movement', title: 'Sprint jump', description: 'Movement burst for gaps.', status: 'extended' },
  { id: 'collect_redstone_dust', category: 'gathering', title: 'Redstone', description: 'Dust for basic circuits.', status: 'extended' },
  { id: 'wave_at_nearby_player', category: 'social', title: 'Wave', description: 'Look at another player and swing arm.', status: 'extended' },
  { id: 'glance_behind', category: 'movement', title: 'Glance back', description: 'Quick look behind (human paranoia).', status: 'extended' },

  ...HUMAN_PLAY_CATALOG,
];

function catalogStats() {
  const by = { core: 0, 'live-addon': 0, stub: 0 };
  for (const e of SKILL_CATALOG) {
    by[e.status] = (by[e.status] || 0) + 1;
  }
  return { total: SKILL_CATALOG.length, byStatus: by };
}

function catalogIds() {
  return SKILL_CATALOG.map((e) => e.id);
}

module.exports = { SKILL_CATALOG, catalogStats, catalogIds };
